FROM python
COPY . . 
RUN pip3 install flask
RUN pip3 install requests
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y apt-utils
RUN apt-get install sqlite3 libsqlite3-dev -y
RUN sqlite3 userdb.db < user.sql
ENV TEAM_NAME=CC_1492_1730_1767_1867
ENTRYPOINT python3 user.py
 
